### ISSUE TITLE
image-set syntax and fallback with url()

### ISSUE THREAD

**Issue by yoanmalie** [csstools/postcss-image-set-function#5]
Hi!
I'm new in the PostCSS community and i started to use postcss-preset-env today.
I faced quickly to an issue about `image-set()` by looking the [postcss-preset-env Playground](https://preset-env.cssdb.org/playground).

If you set `>1%`  for the browserlist compatibily instead of `> 3%`, you will see that the fallback for `background-image` does not to correspond the spec. The url should be noted inside `url("")` like `background-image: url("img/background.jpg");`.

An other issue is that inside the `image-set` property, url should **not** be noted inside `url("")` as [the spec](https://drafts.csswg.org/css-images-4/#image-set-notation) describe it.

Thanks for the efforts you've made!

**Comment by ai** [comment]
Can you show input, output and expected output?

**Comment by yoanmalie** [comment]
Here the input :
```css
.hero:matches(main, .main) {
  background-image: image-set("img/background.jpg" 1x, "img/background-2x.jpg" 2x);
}
```

And the output :
```css
main.hero, .hero.main {
  background-image: img/background.jpg;
}
@media(-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi) {
    main.hero, .hero.main {
        background-image: img/background-2x.jpg;
    }
}
main.hero, .hero.main {
  background-image: -webkit-image-set(url("img/background.jpg") 1x, url("img/background-2x.jpg") 2x);
  background-image: image-set("img/background.jpg" 1x, "img/background-2x.jpg" 2x);
}
```

Expected output :
```css
main.hero, .hero.main {
    background-image: url("img/background.jpg");
}
@media(-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi) {
    main.hero, .hero.main {
        background-image: url("img/background-2x.jpg");
    }
}
main.hero, .hero.main {
  background-image: -webkit-image-set(url("img/background.jpg") 1x, url("img/background-2x.jpg") 2x);
  background-image: image-set("img/background.jpg" 1x, "img/background-2x.jpg" 2x);
}
```

The main problem is the missing `url("")` on the `background-image` property.

EDIT :
In the doc of [postcss-image-set-function](https://github.com/jonathantneal/postcss-image-set-function), the example is showed with `url()`. It should not.

```css
.example {
  background-image: image-set(
    url(img.png) 1x,
    url(img@2x.png) 2x,
    url(img@print.png) 600dpi
  );
}
```
Should be:
```css
.example {
  background-image: image-set(
    "img.png" 1x,
    "img@2x.png" 2x,
    "img@print.png" 600dpi
  );
}
```
