### ISSUE TITLE
support for multiple background images

### ISSUE THREAD

**Issue by emma-sg** [csstools/postcss-image-set-function#7]
hey! having an issue with this where a gradient on top of a background image doesn't survive the transformation.

simplified test case:

```css
/* input */
.example {
  background-image: linear-gradient(#4444, #8888),
    image-set(url(img.png) 1x, url(img@2x.png) 2x);
}

/* expected output */
.example {
  background-image: linear-gradient(#4444, #8888), url(img.png);
}

@media (-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi) {
  .example {
    background-image: linear-gradient(#4444, #8888), url(img@2x.png);
  }
}

/* actual output */
.example {
  background-image: url(img.png);
}

@media (-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi) {
  .example {
    background-image: url(img@2x.png);
  }
}
```

i'll be able to have a crack at fixing it in maybe a week or two when i have some free time.
